### PR TITLE
SAL Azure integration + AzureInfrastructure refactoring

### PR DESCRIPTION
**Pull request by mbenguig**

### CODE REVIEW

**Review by ankicabarisic — APPROVED** [review]
The build is failing. Please check it before merge.

**Comment by mbenguig** [comment]
> The build is failing. Please check it before merge.

Ok.. maybe due to my code refactoring. I will check today

**Comment by mbenguig** [comment]
Retest this please.

**Comment by ankicabarisic** [comment]
it still gives you one failing check - have no idea if is due to your PR or general problem with this project

**Comment by mbenguig** [comment]
Retest this please.

**Comment by fviale** [comment]
Retest this please

**Pull request merged**
